<a href="https://colab.research.google.com/github/Rahulcva/Housing-Prices-Prediction/blob/main/simple_linear_implementation_for_housing_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
class simplelinearregression:
    def __init__(self):
        self.m=None
        self.b=None
    def fit(self,x_train,y_train):
        numeriator=0
        denominator=0
        for i in range(len(x_train)):
            numeriator=numeriator+((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
            denominator=denominator+((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))
        self.m=numeriator/denominator
        self.b=y_train.mean()-(self.m*x_train.mean())
        print(self.m)
        print(self.b)

    def predict(self,x_test):
        print(x_test)
        return self.m*x_test+self.b

In [49]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


***Load the kaggle data ***

In [142]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/housing-prices-dataset")
data_path = path + '/Housing.csv'  # Replace with the correct path and filename
df = pd.read_csv(data_path)

In [51]:
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [52]:
#because we working on simple linear problem so we take only one column as input

In [108]:
X=df.iloc[:,1:2] #that is area

In [109]:
X

area
0    7420
1    8960
2    9960
3    7500
4    7420
..    ...
540  3000
541  2400
542  3620
543  2910
544  3850

[545 rows x 1 columns]

In [118]:
Y=df.iloc[:,0:1]

In [119]:
Y

price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [120]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=2)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(381, 1)
(164, 1)
(381, 1)
(164, 1)


In [121]:
#using skelearn
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [122]:
from sklearn.metrics import r2_score
y_pred=lr.predict(x_test.values.reshape(-1,1))
r2_score(y_test,y_pred)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


0.26532855569542735

In [123]:
x_test

area
333  3000
84   3760
439  3930
396  3640
161  6100
..    ...
117  3700
314  4040
340  5300
444  3120
307  4080

[164 rows x 1 columns]

In [124]:
y_test

price
333  3920000
84   6510000
439  3255000
396  3500000
161  5460000
..       ...
117  5950000
314  4095000
340  3850000
444  3220000
307  4165000

[164 rows x 1 columns]

In [138]:
lr.predict(x_test.iloc[0].values.reshape(1,1))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[3730187.62601536]])

In [126]:
m=lr.coef_

In [127]:
b=lr.intercept_

In [128]:
#m*x+b
m*3000+b

array([[3730187.62601536]])

In [129]:
#using our class

In [130]:
slr=simplelinearregression()


In [131]:
x1 = df.iloc[:,1:2].values  # Access the second column (index 1)
y1 = df.iloc[:, 0:1].values  # Access the first column (index 0)


In [132]:
x_train1,x_test1,y_train1,y_test1=train_test_split(x1,y1,test_size=0.3,random_state=2)

In [133]:
x_train1

array([[ 7800],
       [ 2275],
       [ 4820],
       [ 5640],
       [ 4840],
       [ 6000],
       [ 4400],
       [ 6800],
       [ 4000],
       [ 8400],
       [ 4400],
       [ 6000],
       [ 5500],
       [ 3650],
       [ 5136],
       [ 2700],
       [ 4240],
       [ 2650],
       [ 6040],
       [ 9800],
       [ 4050],
       [ 7160],
       [ 6650],
       [ 4000],
       [ 6450],
       [ 3090],
       [ 3180],
       [ 6000],
       [ 4770],
       [ 7000],
       [ 7475],
       [ 3934],
       [ 3180],
       [13200],
       [ 4992],
       [ 4600],
       [ 8500],
       [ 4950],
       [ 5300],
       [ 2145],
       [ 6300],
       [ 3600],
       [ 7020],
       [ 4500],
       [ 4040],
       [ 6321],
       [ 3640],
       [ 6540],
       [ 5500],
       [ 5500],
       [ 3520],
       [10500],
       [ 2700],
       [ 3850],
       [ 4360],
       [ 4800],
       [ 4130],
       [ 3240],
       [ 5450],
       [ 6000],
       [ 3450],
       [ 5680],
       [

In [134]:
y_train1

array([[ 5320000],
       [ 3640000],
       [ 3780000],
       [ 3675000],
       [ 4165000],
       [ 7350000],
       [ 4305000],
       [ 6020000],
       [ 2730000],
       [ 3780000],
       [ 5565000],
       [ 6860000],
       [ 5873000],
       [ 5530000],
       [ 5600000],
       [ 3353000],
       [ 3500000],
       [ 2800000],
       [ 4830000],
       [ 5250000],
       [ 3710000],
       [ 5880000],
       [ 4235000],
       [ 6790000],
       [ 5383000],
       [ 3080000],
       [ 3640000],
       [ 6629000],
       [ 4900000],
       [ 5803000],
       [ 8400000],
       [ 2660000],
       [ 3290000],
       [ 9800000],
       [ 4060000],
       [ 3010000],
       [ 8960000],
       [ 4382000],
       [ 2233000],
       [ 3332000],
       [ 4900000],
       [ 3500000],
       [ 5950000],
       [ 3570000],
       [ 4480000],
       [ 4760000],
       [ 2345000],
       [ 5250000],
       [ 5600000],
       [ 8400000],
       [ 4200000],
       [ 5600000],
       [ 294

In [135]:
slr.fit(x_train1,y_train1)

[481.58851797]
[2285422.07211824]


In [136]:
m

array([[481.58851797]])

In [137]:
b

array([2285422.07211824])

In [141]:
slr.predict(x_test1[0])

[3000]


array([3730187.62601536])